### ISSUE TITLE
A better way to create emails

### ISSUE THREAD

**Issue by vezycash** [r0hi7/Trashemail#10]
/create myemail@trashemail.in 

This is unnessarily long.  It should be 

**/create myemail**

******

Even if you have multiple domains, users shouldn't have to type the full domain. 

**Step 1:** /create myemail

**Step 2:** [prompt chose one of these domains for your new email]
1. newtrashemail.in
2. trashemail.in

Step 3: Congratulations. Your new email is xese@newtrashemail.in

**Comment by r0hi7** [comment]
I will take this input.

**Comment by r0hi7** [comment]
Address in d718a67, thanks @vezycash  for motivating for this. Now the UX is definitely better.
