### ISSUE TITLE
One email delivered twice on telegram

### ISSUE THREAD

**Issue by dcRUSTy** [r0hi7/Trashemail#17]
**Describe the bug**
(Improper Email address parsing)? leads to multiple messages on telegram.

Example
1) If Recipient is `John Doe<jdoe@machine.example>` here John Doe is name and `jdoe@machine.example` is email
2) If Recipient is `jdoe1@machine.example<jdoe@machine.example>` here `jdoe1@machine.example` is name and `jdoe@machine.example` is email address.
**Now the Buggy case** 
3) Similiarly If Recipient is `jdoe@machine.example<jdoe@machine.example>` here `jdoe@machine.example` is name and email address. It should be delivered once. but is delivered twice on telegram.

**To Reproduce**
1. Create a new trashemail id say `trash@trashemail.in`
2. Compose an email to `trash@trashemail.in<trash@trashemail.in>`

**Expected behavior**
Email should be received once on Telegram.

**Actual behavior**
Email is received twice on Telegram.

**Comment by r0hi7** [comment]
It was the issues with the way emails were parsed. This is now getting fixed. Thanks for pointing this out. @dcRUSTy
