### ISSUE TITLE
Can't create a new temp email.

### ISSUE THREAD

**Issue by Suleman-Elahi** [r0hi7/Trashemail#19]
**Describe the bug**

Can't register a new temp email on the bot. It says: "Something bad just happened with me. Stay back till I get fixed"

**To Reproduce**

1. Install bot.
2. Create a new email.
3. See error

**Expected behavior**

Should create a new email to receive emails.

**Screenshots**
![Screenshot_20200601-145030_Telegram](https://user-images.githubusercontent.com/24384996/83395227-8ae9c280-a417-11ea-87bb-4401e8955beb.jpg)

**Smartphone (please complete the following information):**
 - Device: Android, Samsung M40
 - OS: Android 10

**Comment by r0hi7** [comment]
@Suleman-Elahi  This is just display bug. Actually the user is getting created but the there in code by mistake it was written for all successful creations the this message was being thrown.
https://github.com/r0hi7/Trashemail/blob/6819a7648f917c8b428208560772929d9f6a2d95/src/main/java/io/github/trashemail/Telegram/TelegramRequestHandler.java#L119

Thanks again for pointing this out.

**Comment by r0hi7** [comment]
Fixed in 6819a76
