### ISSUE TITLE
What did you do to get banned on twimtor?

### ISSUE THREAD

**Issue by JustACuteGirlLookingForAManToFixHerBugs** [r0hi7/TrashEmail#75]
Gotta update the link in the bot c:

**Comment by r0hi7** [comment]
Oh yes my twitter handle is changed ... Thanks for ping. I will update.

**Comment by r0hi7** [comment]
I changed my twitter handle and forgot to update the same. Now I have update it in the code. You are good to go and dont forget to follow me on twitter :P @JustACuteGirlLookingForAManToFixHerBugs
