### ISSUE TITLE
🥒 Severe issue with 'HTML version'

### ISSUE THREAD

**Issue by JustACuteGirlLookingForAManToFixHerBugs** [r0hi7/TrashEmail#76]
HTML version link is not working for me. Try it yourself: https://trashemail.in/mails/0f3d5bb2-68ab-4d3e-a06b-3fc1319d948c.html

It's a major issue for this one - there should be a download button in the letter. But other links don't work either.

**Comment by r0hi7** [comment]
Sorry for that. I checked it, it's indeed not working... I will check and fix it.

**Comment by aditya-shri** [comment]
Is it fixed?

**Comment by r0hi7** [comment]
Not yet. Will be done today hopefully 😀

**Comment by r0hi7** [comment]
Fixed, thanks for the motivation @aditya-shri  and @JustACuteGirlLookingForAManToFixHerBugs
